org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.java.installations.auto-download=true

# Fabric (Minecraft 26.2)
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Fabric API modules
deps.keymap=2.0.5+e2bdee789e
deps.msg=7.0.7+086d547a9e
deps.render=25.3.1+6988455e9e
deps.lifecycle=4.1.3+4575b05f9e

# Mod metadata
mod.id=lavamenu
mod.name=Lava Menu
mod.version=0.2.0
mod.description=Меню быстрых команд для сервера (AH, точки, анимации, чаты).
mod.author=mzrb
mod.mcdep=~26.2
maven_group=ru.lava
