org.gradle.jvmargs=-Xmx2G
org.gradle.java.installations.auto-download=true

# Modstitch
modstitch.platform=fabric-loom

# Deps
deps.mc=26.1.2
deps.fabric=0.18.4
deps.fapi=0.143.14+26.1
deps.keymap=2.0.4+e2bdee78c3
deps.msg=7.0.4+e2bdee78c3
deps.render=23.0.2+f348b6c3c3

# Mod metadata
mod.id=lavamenu
mod.name=Lava Menu
mod.version=0.1.10
mod.description=Меню быстрых команд для сервера (AH, точки, анимации, чаты).
mod.author=mzrb
mod.mcdep=~26.1

